# Site settings
title:  Tien Blog
SEOTitle: 风野博客 | Tien Blog
#header-img: img/home-bg.jpg
email: willtien@outlook.com
description: "业精于勤荒于嬉，行成于思毁于随。"
keyword: ""
url: "http://willtien.com"  
baseurl: "/Projects"

